SWBiblioteca/Controllers/EditorialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWBiblioteca.Data;
using SWBiblioteca.Entity;

namespace SWBiblioteca.Controllers
{
    [Authorize]
    public class EditorialController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EditorialController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> Index()
        {
            var lista = await _context.EDITORIAL.ToListAsync();
            return View(lista);
        }

        public async Task<ActionResult> Modal(int id)
        {
            var model = new EDITORIAL();
            if (id > 0)
            {
                model = await _context.EDITORIAL.FindAsync(id);
            }
            var estados = _context.ESTADOS.ToList();
            ViewData["Lista_Estados"] = new SelectList(estados.OrderBy(t => t.Descripcion), "Valor", "Descripcion", model.Estado);

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(EDITORIAL editorial)
        {
            try
            {
                var model = await _context.EDITORIAL.FindAsync(editorial.IdEditorial);
                if (model != null)
                {
                    model.Descripcion = editorial.Descripcion;
                    model.Estado = editorial.Estado;
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    editorial.FechaCreacion = DateTime.Now.Date;
                    _context.Add(editorial);
                    await _context.SaveChangesAsync();
                }
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                if (id > 0)
                {
                    var model = await _context.EDITORIAL.FindAsync(id);

                    _context.EDITORIAL.Remove(model);
                    await _context.SaveChangesAsync();
                }
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

SWBiblioteca/Views/Editorial/Index.cshtml
@model IEnumerable<EDITORIAL>
@{

}

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary">
        <h6 class="m-0 font-weight-bold text-white">Lista de Editoriales</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <a asp-action="Modal" class="btn btn-success btn-sm guardar-dialog-window" type="button">Crear Nuevo</a>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered" id="tabla" style="width:100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Descricion</th>
                                <th>Estado</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Descripcion)
                                    </td>
                                    <td>
                                        @if (item.Estado)
                                        {
                                            <span class="badge badge-success p-2">Activo</span>
                                        }else
                                        {
                                            <span class="badge badge-danger p-2">Inactivo</span>
                                        }
                                    </td>
                                    <td>
                                        <a asp-action="Modal" asp-route-id="@item.IdEditorial" class="btn btn-primary btn-sm guardar-dialog-window"><i class="fas fa-pen"></i></a>
                                        <a data-id="@item.IdEditorial.ToString()" class="btn btn-danger btn-sm ml-2 eliminar-dialog-window"><i class="fas fa-trash"></i></a>
                                    </td>
                                </tr>
                            }        
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="exampleModalLabel">Editorial</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="teeee">Please wait...</div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="Delete" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-danger text-white">
                <h5 class="modal-title" id="exampleModalLabel">Mensaje</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <h5>¿Estas seguro de eliminar el registro seleccionado?</h5>
                </div>
                <div id="response" class="text-right">
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        var tabladata;
        $(document).ready(function () {
            tabladata = $('#tabla').DataTable({
                responsive:true,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                }
            });
        });

        $("body").on("click", "a.guardar-dialog-window", null, function (e) {
            e.preventDefault();
            var $link = $(this);
            var url = $(this).attr('href');
            if (url.indexOf('#') == 0) {
                $('#FormModal').modal('show');
            }
            else {
                $.get(url, function (data) {
                    $('#FormModal .teeee').html(data);
                    $('#FormModal').modal();
                })
            }
        });

        $("body").on("click", "a.eliminar-dialog-window", null, function (e) {
            var htmlContent = '<div class="modal-footer"><button type="button" id="btnNo" class="btn btn-danger" data-dismiss="modal" aria-hidden="true">No</button><a onclick=Eliminar(' + $(this).data('id') + ') class="btn btn-primary">Si</a></div>';
            $("#response").html(htmlContent);
            $('#Delete').modal('show');
        });


        function Guardar() {
            $('.errorForm').remove();
            let descripción = $("#txtdescripcion").val();
            if(descripción.trim() == ""){
                $("#txtdescripcion").after('<span class="errorForm text-danger">Favor de ingresar la descripción</span>');
                return false;
            }

            var objCategoria = new Object();
            objCategoria.IdEditorial = $("#txtid").val();
            objCategoria.Descripcion = $("#txtdescripcion").val();
            objCategoria.Estado = $("#cboEstado").val();
            debugger
            jQuery.ajax({
                type: "POST",
                url: '@Url.Action("Guardar", "Editorial")',
                dataType: "json",
                data: objCategoria,
                success: function (data) {
                    if (data) {
                        $('#FormModal').modal('hide');
                        swal({
                            title: "Tu editorial se guardo con exito!",
                            icon: "success",
                            button: "Aceptar",
                        }).then((value) => {
                            refrescar();
                        });
                    } else {
                        swal({
                            title: "No se pudo guardar los cambios!",
                            icon: "error",
                            button: "Aceptar",
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                },
            });
        }

        function Eliminar(idCategoria) {
            debugger
            jQuery.ajax({
                type: "POST",
                url: '@Url.Action("Eliminar", "Editorial")',
                dataType: "json",
                data: { id : idCategoria },
                success: function (data) {
                    debugger
                    if (data) {
                        $('#Delete').modal('hide');
                        swal({
                            title: "La editorial seleccionada se eliminó con exito!",
                            icon: "success",
                            button: "Aceptar",
                        }).then((value) => {
                            refrescar();
                        });
                    } else {
                        swal({
                            title: "No se pudo eliminar el editorial seleccionado!",
                            icon: "error",
                            button: "Aceptar",
                        });
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {
                },
            });
        }

    </script>
}

SWBiblioteca/Views/Editorial/Modal.cshtml
@model EDITORIAL
<form id="formNivel">
    <input type="hidden" asp-for="IdEditorial" id="txtid" />
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <label for="txtdescripcion">Descripcion:</label>
                <input asp-for="Descripcion" type="text" class="form-control required" id="txtdescripcion">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <label for="cboEstado">Estado:</label>
                <select asp-for="Estado" asp-items="ViewBag.Lista_Estados" id="cboEstado" class="form-control"></select>
            </div>
        </div>
    </div>
</form>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
    <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
</div>