SWBiblioteca/Controllers/AutorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWBiblioteca.Data;
using SWBiblioteca.Entity;

namespace SWBiblioteca.Controllers
{
    [Authorize]
    public class AutorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AutorController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<ActionResult> Index()
        {
            var lista = await _context.AUTOR.ToListAsync();
            return View(lista);
        }

        public async Task<ActionResult> Modal(int id)
        {
            var model = new AUTOR();
            if (id > 0)
            {
                model = await _context.AUTOR.FindAsync(id);
            }
            var estados = _context.ESTADOS.ToList();
            ViewData["Lista_Estados"] = new SelectList(estados.OrderBy(t => t.Descripcion), "Valor", "Descripcion", model.Estado);

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(AUTOR autor)
        {
            try
            {
                var model = await _context.AUTOR.FindAsync(autor.IdAutor);
                if (model != null)
                {
                    model.Descripcion = autor.Descripcion;
                    model.Estado = autor.Estado;
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    autor.FechaCreacion = DateTime.Now.Date;
                    _context.Add(autor);
                    await _context.SaveChangesAsync();
                }
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                if (id > 0)
                {
                    var model = await _context.AUTOR.FindAsync(id);

                    _context.AUTOR.Remove(model);
                    await _context.SaveChangesAsync();
                }
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

SWBiblioteca/Controllers/LibroController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWBiblioteca.Data;
using SWBiblioteca.Entity;

using SWBiblioteca.Clases;
using Microsoft.Extensions.Hosting.Internal;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;

namespace SWBiblioteca.Controllers
{
    [Authorize]
    public class LibroController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;
        public LibroController(ApplicationDbContext context, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<ActionResult> Index()
        {
            var lista = await _context.LISTAR_LIBROS_Q01.FromSqlRaw("LISTAR_LIBROS_Q01").ToListAsync();
            return View(lista);
        }

        public async Task<ActionResult> Modal(int id)
        {
            var model = new LIBRO();
            if (id > 0)
            {
                model = await _context.LIBRO.FindAsync(id);
            }
            #region Combos
            var estados = _context.ESTADOS.ToList();
            estados.Add(new ESTADOS { Id_Estado = 0, Descripcion = "Seleccionar" });
            ViewData["Lista_Estados"] = new SelectList(estados.OrderBy(t => t.Descripcion), "Valor", "Descripcion", model.Estado);

            var autores = _context.AUTOR.Where(z => z.Estado).ToList();
            autores.Add(new AUTOR { IdAutor = 0, Descripcion = "Seleccionar" });
            ViewData["Lista_Autores"] = new SelectList(autores.OrderBy(t => t.Descripcion), "IdAutor", "Descripcion", model.IdAutor);

            var categorias = _context.CATEGORIA.Where(z => z.Estado).ToList();
            categorias.Add(new CATEGORIA { IdCategoria = 0, Descripcion = "Seleccionar" });
            ViewData["Lista_Categorias"] = new SelectList(categorias.OrderBy(t => t.Descripcion), "IdCategoria", "Descripcion", model.IdCategoria);

            var editoriales = _context.EDITORIAL.Where(z => z.Estado).ToList();
            editoriales.Add(new EDITORIAL { IdEditorial = 0, Descripcion = "Seleccionar" });
            ViewData["Lista_Editoriales"] = new SelectList(editoriales.OrderBy(t => t.Descripcion), "IdEditorial", "Descripcion", model.IdEditorial);
            #endregion

            return PartialView(model);
        }


        [HttpPost]
        public async Task<IActionResult> Guardar(string objeto, IFormFile imagen)
        {
            try
            {
                var libro = JsonConvert.DeserializeObject<LIBRO>(objeto);
                var model = await _context.LIBRO.FindAsync(libro.IdLibro);
                if (model != null)
                {
                    model.Titulo = libro.Titulo;
                    model.IdAutor = libro.IdAutor;
                    model.IdCategoria = libro.IdCategoria;
                    model.IdEditorial = libro.IdEditorial;
                    model.Ubicacion = libro.Ubicacion;
                    model.Ejemplares = libro.Ejemplares;
                    model.Estado = libro.Estado;
                    if (imagen != null)
                    {
                        List<string> lista = await Util.UploadDocument(_hostingEnvironment, imagen, "ImgLibros/");
                        model.NombrePortada = lista[0];
                        model.RutaPortada = lista[1];
                    }
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    if (imagen != null)
                    {
                        List<string> lista = await Util.UploadDocument(_hostingEnvironment, imagen, "ImgLibros/");
                        libro.NombrePortada = lista[0];
                        libro.RutaPortada = lista[1];
                    }
                    libro.FechaCreacion = DateTime.Now.Date;
                    _context.Add(libro);
                    await _context.SaveChangesAsync();
                }
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

    }
}

SWBiblioteca/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SWBiblioteca.Clases;
using SWBiblioteca.Data;
using SWBiblioteca.Entity;
using SWBiblioteca.Entity.Procedure;
using SWBiblioteca.Models;
using SWBiblioteca.Resources;
using SWBiblioteca.Services.Contract;

namespace SWBiblioteca.Controllers
{
    public class PersonaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailService _emailService;

        public PersonaController(ApplicationDbContext dbContext, IEmailService emailService)
        {
            _context = dbContext;
            _emailService = emailService;
        }

        public async Task<ActionResult> Index(DateTime? fecInicio, DateTime? fecFinal) 
        {
            #region Filtros
            //var fechaActual = DateTime.Now.Date;
            //var inicioMes = new DateTime(fechaActual.Year, fechaActual.Month, 1);
            //var finalMes = inicioMes.AddMonths(1).AddDays(-1);

            fecInicio = fecInicio == null ? null : fecInicio;
            fecFinal = fecFinal == null ? null : fecFinal;
            #endregion

            var lista = await _context.PR_PERSONA_Q01.FromSqlRaw("PR_PERSONA_Q01 @p0,@p1", fecInicio, fecFinal).ToListAsync();
            var consultaPerfilValid = _context.CONSULTAR_PERFIL_Q01.FromSqlRaw("CONSULTAR_PERFIL_Q01 @p0,@p1", "Validador", User.Identity.Name).ToList();
            var respuesta = 0;
            if (consultaPerfilValid.Count() > 0)
            {
                respuesta = 1;
                lista = lista.Where(z => z.TipoPersona == "Lector").ToList();
            }
            ViewBag.Validador = respuesta;

            foreach (var item in lista)
            {
                var consulta = _context.LOG_PERSONA.Where(z => z.Cod_Usuario == item.Codigo).OrderByDescending(z => z.Id_LogPersona).FirstOrDefault();
                if (consulta != null)
                {
                    item.Validacion = consulta.Estado;
                }
            }

            return View(lista);
        }

        public async Task<ActionResult> Modal(int id)
        {
            var model = new PERSONA();
            if (id > 0)
            {
                model = await _context.PERSONA.FindAsync(id);
            }

            #region Combos
            var estados = _context.ESTADOS.ToList();
            ViewData["Lista_Estados"] = new SelectList(estados.OrderBy(t => t.Descripcion), "Valor", "Descripcion", model.Estado);

            var tipoPersonas = _context.TIPO_PERSONA.Where(z => z.Estado).ToList();
            ViewData["Lista_TipPersonas"] = new SelectList(tipoPersonas.OrderBy(t => t.Descripcion), "IdTipoPersona", "Descripcion", model.IdTipoPersona);
            #endregion

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(PERSONA persona)
        {
            try
            {
                var model = await _context.PERSONA.FindAsync(persona.IdPersona);
                if (model != null)
                {
                    model.Nombre = persona.Nombre;
                    model.Apellido = persona.Apellido;
                    model.Correo = persona.Correo;
                    if (!String.IsNullOrEmpty(persona.NewClave))
                    {
                        model.Clave = Utilities.EncryptKey(persona.Clave);
                    }
                    model.Codigo = persona.Codigo;
                    model.IdTipoPersona = persona.IdTipoPersona;
                    model.Estado = persona.Estado;
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    if (!String.IsNullOrEmpty(persona.NewClave))
                    {
                        persona.Clave = Utilities.EncryptKey(persona.NewClave);
                    }
                    persona.FechaCreacion = DateTime.Now.Date;
                    _context.Add(persona);
                    await _context.SaveChangesAsync();
                }
                return Json(new { valor = true, message = "Tu categoría se guardo con exito!" });
            }
            catch (Exception ex)
            {
                return Json(new { valor = false, message = ex.Message });
            }
        }

        public async Task<ActionResult> ModalResetPassword(int id)
        {
            var model = new PERSONA();
            if (id > 0)
            {
                model = await _context.PERSONA.FindAsync(id);
            }
            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(int id, string password)
        {
            try
            {
                var model = await _context.PERSONA.FindAsync(id);
                if (model != null)
                {
                    if (!String.IsNullOrEmpty(password))
                    {
                        model.Clave = Utilities.EncryptKey(password);
                    }
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    return Json(new { valor = true, message = "Se cambio la contraseña con éxito!" });
                }
                else 
                {
                    return Json(new { valor = false, message = "No se pudo cambiar la contraseña!" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { valor = false, message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                if (id > 0)
                {
                    var model = await _context.PERSONA.FindAsync(id);

                    _context.PERSONA.Remove(model);
                    await _context.SaveChangesAsync();
                }
                return Json(new { valor = true, message = "EL usuario seleccionado se eliminó con exito!" });
            }
            catch (Exception ex)
            {
                return Json(new { valor = false, message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Aceptar(int id)
        {
            try
            {
                if (id > 0)
                {
                    var model = await _context.PERSONA.FindAsync(id);
                    model.Estado = true;
                    _context.PERSONA.Update(model);
                    await _context.SaveChangesAsync();

                    var log = new LOG_PERSONA();
                    log.Cod_Usuario = model.Codigo;
                    log.Cod_Validador = User.Identity.Name;
                    log.Estado = "Aceptado";
                    log.FechaRegistro = DateTime.Now.Date;
                    log.HoraRegistro = DateTime.Now.TimeOfDay;
                    _context.LOG_PERSONA.Update(log);
                    await _context.SaveChangesAsync();

                    var cuerpo = $"<p>Estimado {model.Nombre} {model.Apellido}, es grato informarle que su registro fue aceptado. Ahora ya puede acceder a la web Biblioteca Xander.</p>"
                        + "<p>¡Que tenga buen día!</p>";

                    var request = new EmailDTO();
                    request.For = "agalexander63@gmail.com";
                    request.Affair = "XANDER BIBLIOTECA: REGISTRO ACEPTADO";
                    request.Content = Util.EmailBody(cuerpo);
                    _emailService.SendEmail(request);

                }
                return Json(new { valor = true, message = "EL usuario seleccionado se acepto con exito!" });
            }
            catch (Exception ex)
            {
                return Json(new { valor = false, message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Rechazar(int id)
        {
            try
            {
                if (id > 0)
                {
                    var model = await _context.PERSONA.FindAsync(id);
                    model.Estado = false;
                    _context.PERSONA.Update(model);
                    await _context.SaveChangesAsync();

                    var log = new LOG_PERSONA();
                    log.Cod_Usuario = model.Codigo;
                    log.Cod_Validador = User.Identity.Name;
                    log.Estado = "Rechazado";
                    log.FechaRegistro = DateTime.Now.Date;
                    log.HoraRegistro = DateTime.Now.TimeOfDay;
                    _context.LOG_PERSONA.Update(log);
                    await _context.SaveChangesAsync();

                    var cuerpo = $"<p>Estimado {model.Nombre} {model.Apellido}, aprovecho la presente para informarle que su registro fue rechazado debido a DNI o Carné de Extrangeria no encontrada en SUNAT.</p>"
                        + "<p>Favor de volver a registrarse con datos correctos.</p>"
                        + "<p>¡Que tenga buen día!</p>";

                    var request = new EmailDTO();
                    request.For = "agalexander63@gmail.com";
                    request.Affair = "XANDER BIBLIOTECA: REGISTRO RECHAZADO";
                    request.Content = Util.EmailBody(cuerpo);
                    _emailService.SendEmail(request);
                }
                return Json(new { valor = true, message = "EL usuario seleccionado se rechazo con exito!" });
            }
            catch (Exception ex)
            {
                return Json(new { valor = false, message = ex.Message });
            }
        }

    }
}

SWBiblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWBiblioteca</title>
    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <!-- Custom styles for this page -->
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a asp-controller="Home" asp-action="Index" class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-book-reader"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Biblioteca</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a asp-controller="Home" asp-action="Index" class="nav-link">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Módulos
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne"
                   aria-expanded="true" aria-controls="collapseOne">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>Configuración</span>
                </a>
                <div id="collapseOne" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Persona" asp-action="Index">Usuarios</a>
                        <a class="collapse-item" href="cards.html">Perfiles</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Gestión
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Prestamos</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="login.html">Registrar</a>
                        <a class="collapse-item" href="register.html">Consultas</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThre"
                   aria-expanded="true" aria-controls="collapseThre">
                    <i class="fas fa-fw fa-book"></i>
                    <span>Biblioteca</span>
                </a>
                <div id="collapseThre" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Libro" asp-action="Index">Libros</a>
                        <a class="collapse-item" asp-controller="Autor" asp-action="Index">Autores</a>
                        <a class="collapse-item" asp-controller="Editorial" asp-action="Index">Editorial</a>
                        <a class="collapse-item" asp-controller="Categoria" asp-action="Index">Categoria</a>
                    </div>
                </div>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <i class="fas fa-user-shield" style="font-size:25px;font-weight:bold"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("LogOff","Login")">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cerrar Sesión
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2023 - SWBiblioteca by <a href="https://alexandergomez.netlify.app/">Alexander Gomez</a></span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->

    </div>

    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    <!-- Page level plugins -->
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/datatables-demo.js"></script>

    <!--Alertas-->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        const refrescar = () => {
            location.reload();
        };
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>